import Link from "next/link";
import { notFound } from "next/navigation";

type Demo = {
  slug: string;
  title: string;
  eyebrow: string;
  headline: string;
  description: string;
  action: string;
  color: string;
  soft: string;
  items: [string, string, string][];
};

const demos: Demo[] = [
  { slug: "corporate", title: "Corporate / Agency", eyebrow: "Strategy, design & growth", headline: "The partner behind your next confident move.", description: "A polished agency layout for service businesses that need authority, proof and a direct path to a conversation.", action: "Start a project", color: "#2563eb", soft: "#dbeafe", items: [["Brand strategy", "Positioning systems that make decisions easier.", "01"], ["Digital experiences", "Websites designed to turn attention into action.", "02"], ["Growth campaigns", "Practical campaigns with transparent performance.", "03"]] },
  { slug: "restaurant", title: "Restaurant", eyebrow: "Modern neighbourhood dining", headline: "Dinner worth lingering over.", description: "A restaurant home page with a signature menu, reservation call-to-action and atmosphere-led storytelling.", action: "Book a table", color: "#b45309", soft: "#fef3c7", items: [["Charred sea bass", "Lemon butter, fennel and herb salad.", "$28"], ["Saffron chicken", "Fragrant rice, pickled onion and yogurt.", "$24"], ["Basque cheesecake", "Vanilla cream and berry compote.", "$11"]] },
  { slug: "furniture", title: "Furniture", eyebrow: "Thoughtful living", headline: "Furniture made for the way you live.", description: "A warm product-led storefront for collections, room inspiration and considered materials.", action: "Shop collections", color: "#7c5a3c", soft: "#f3e8dc", items: [["Arc lounge chair", "Sculpted oak with woven linen upholstery.", "$680"], ["Gather dining table", "Generous proportions in natural ash.", "$1,240"], ["Quiet sideboard", "Soft-close storage with a hand-finished top.", "$920"]] },
  { slug: "fashion", title: "Fashion", eyebrow: "New season / 2026", headline: "Everyday pieces, beautifully considered.", description: "An editorial fashion layout that balances a strong campaign message with shoppable essentials.", action: "Shop the edit", color: "#be185d", soft: "#fce7f3", items: [["Studio trench", "A fluid cotton layer for changing weather.", "$210"], ["Wide-leg trouser", "Tailored comfort in a soft wool blend.", "$140"], ["Everyday knit", "Fine merino with a relaxed shape.", "$120"]] },
  { slug: "real-estate", title: "Real Estate", eyebrow: "Homes with a sense of place", headline: "Find the space that fits your next chapter.", description: "A search-led property layout with featured homes, local expertise and viewing calls-to-action.", action: "Browse homes", color: "#047857", soft: "#d1fae5", items: [["Garden residence", "Light-filled 4 bed home near the park.", "$780k"], ["Riverside loft", "Two-bedroom apartment with skyline views.", "$540k"], ["Cedar family home", "Quiet street, generous garden and studio.", "$895k"]] },
  { slug: "salon-beauty", title: "Salon / Beauty", eyebrow: "Hair, skin & self-care", headline: "Make time for feeling like yourself.", description: "A calming salon experience with service cards, practitioner trust and online booking prompts.", action: "Book an appointment", color: "#a21caf", soft: "#fae8ff", items: [["Signature cut & finish", "A tailored cut, treatment and polished finish.", "75 min"], ["Glow facial", "Restorative care customised to your skin.", "60 min"], ["Colour refresh", "Dimensional colour with a nourishing gloss.", "120 min"]] },
  { slug: "travel", title: "Travel", eyebrow: "Journeys with character", headline: "Go further. Come back changed.", description: "An inspiring travel layout for curated itineraries, trust signals and consultation-driven booking.", action: "Plan my trip", color: "#0369a1", soft: "#e0f2fe", items: [["Coastlines of Portugal", "Eight days of food, villages and Atlantic light.", "8 days"], ["Japan after dark", "A considered route through cities, craft and calm.", "11 days"], ["Highlands by foot", "Guided trails and fireside stays in Scotland.", "6 days"]] },
  { slug: "education-coaching", title: "Education / Coaching", eyebrow: "Learn with direction", headline: "Build the skills that move your work forward.", description: "A clear coaching and education page for programmes, outcomes, testimonials and discovery calls.", action: "Explore programmes", color: "#4f46e5", soft: "#e0e7ff", items: [["Lead with clarity", "A six-week programme for confident managers.", "6 weeks"], ["Career reset", "Find your next direction with structured coaching.", "1:1"], ["Team workshops", "Bring shared focus to your next quarter.", "Custom"]] },
  { slug: "electronics", title: "Electronics", eyebrow: "Smart tech, simply chosen", headline: "Better gear for your everyday setup.", description: "A clean electronics storefront focused on product comparison, service confidence and conversion.", action: "Shop technology", color: "#4338ca", soft: "#e0e7ff", items: [["Orbit headphones", "Adaptive sound with all-day comfort.", "$199"], ["Lumen desk lamp", "Focus light with simple touch controls.", "$89"], ["Dock mini", "One compact hub for your work setup.", "$129"]] },
  { slug: "ecommerce", title: "E-commerce", eyebrow: "Useful things, well made", headline: "Small upgrades for everyday life.", description: "A flexible commerce layout for a general shop with featured products, category navigation and trust-building detail.", action: "Shop bestsellers", color: "#ea580c", soft: "#ffedd5", items: [["Everyday bottle", "Insulated steel, made to go everywhere.", "$32"], ["Canvas carryall", "A durable tote with room for the day.", "$46"], ["Sunday candle", "Soft cedar and citrus for slow evenings.", "$24"]] },
];

export default async function TemplatesPage({ params }: { params: Promise<{ template?: string[] }> }) {
  const { template } = await params;
  const selected = template?.[0] ? demos.find((demo) => demo.slug === template[0]) : undefined;
  if (template?.[0] && !selected) notFound();

  if (!selected) {
    return <main className="min-h-screen bg-[#f7f7f5] px-6 py-14 text-slate-950"><header className="mx-auto flex max-w-7xl items-center justify-between"><Link href="/" className="text-lg font-black">Tairanos <span className="font-medium text-slate-400">/ demos</span></Link><a className="rounded-full bg-slate-950 px-4 py-2 text-sm font-bold text-white" href="mailto:tairanos8@gmail.com">Request a custom site</a></header><section className="mx-auto max-w-4xl py-16 text-center"><p className="text-sm font-bold uppercase tracking-[.2em] text-blue-600">Client-ready website demos</p><h1 className="mt-4 text-5xl font-black tracking-tight md:text-7xl">Choose a layout. Make it yours.</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-slate-600">Each demo is a reusable starting point. We tailor the brand, content, products and lead flow for your business.</p></section><section className="mx-auto grid max-w-7xl gap-5 pb-16 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{demos.map((demo, index) => <article className="group relative min-h-80 overflow-hidden rounded-[1.75rem] bg-white p-6 shadow-sm ring-1 ring-slate-200 transition hover:-translate-y-1 hover:shadow-xl" key={demo.slug}><div className="absolute -right-10 -top-10 h-40 w-40 rounded-full" style={{ backgroundColor: demo.color }} /><div className="relative flex h-full flex-col"><div className="flex items-start justify-between"><span className="rounded-full px-3 py-1 text-xs font-black" style={{ backgroundColor: demo.soft, color: demo.color }}>{String(index + 1).padStart(2, "0")}</span><span className="text-4xl font-black text-white">{demo.title.charAt(0)}</span></div><div className="mt-auto"><p className="text-sm font-bold" style={{ color: demo.color }}>{demo.eyebrow}</p><h2 className="mt-2 text-2xl font-black">{demo.title}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{demo.description}</p><Link className="mt-5 inline-block text-sm font-black" style={{ color: demo.color }} href={`/templates/${demo.slug}`}>Open live preview →</Link></div></div></article>)}</section></main>;
  }

  return <main className="min-h-screen bg-stone-50 px-6 py-7 text-slate-950"><header className="mx-auto flex max-w-6xl items-center justify-between"><Link href="/templates" className="text-lg font-black">Tairanos <span className="font-medium text-slate-400">/ {selected.title}</span></Link><a href="#contact" className="rounded-full px-4 py-2 text-sm font-bold text-white" style={{ backgroundColor: selected.color }}>{selected.action}</a></header><section className="mx-auto grid max-w-6xl gap-12 pb-20 pt-16 md:grid-cols-[1.15fr_.85fr] md:items-center"><div><p className="mb-5 text-sm font-bold uppercase tracking-[.18em]" style={{ color: selected.color }}>{selected.eyebrow}</p><h1 className="max-w-3xl text-5xl font-black leading-[.95] tracking-tight md:text-7xl">{selected.headline}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-slate-600">{selected.description}</p><a href="#contact" className="mt-8 inline-block rounded-full px-6 py-3 font-bold text-white" style={{ backgroundColor: selected.color }}>{selected.action}</a></div><div className="relative min-h-80 overflow-hidden rounded-[2rem] p-8" style={{ backgroundColor: selected.soft }}><div className="absolute -right-12 -top-12 h-52 w-52 rounded-full" style={{ backgroundColor: selected.color }} /><div className="absolute bottom-8 left-8 right-8 rounded-3xl bg-white/90 p-6 shadow-xl"><p className="text-sm font-bold" style={{ color: selected.color }}>Designed for {selected.title}</p><p className="mt-2 text-2xl font-black">A reusable, client-ready layout.</p></div></div></section><section className="bg-white py-20"><div className="mx-auto max-w-6xl"><p className="text-sm font-bold uppercase tracking-[.18em]" style={{ color: selected.color }}>Made to convert</p><h2 className="mt-2 text-3xl font-black">Featured highlights</h2><div className="mt-9 grid gap-5 md:grid-cols-3">{selected.items.map(([title, detail, meta], index) => <article className="rounded-3xl border border-slate-200 p-6" key={title}><div className="mb-8 flex h-12 w-12 items-center justify-center rounded-2xl text-lg font-black" style={{ backgroundColor: selected.soft, color: selected.color }}>{String(index + 1).padStart(2, "0")}</div><h3 className="text-xl font-black">{title}</h3><p className="mt-3 min-h-12 leading-6 text-slate-600">{detail}</p><p className="mt-6 font-bold" style={{ color: selected.color }}>{meta}</p></article>)}</div></div></section><section id="contact" className="mx-auto max-w-6xl py-20"><div className="rounded-[2rem] bg-slate-950 p-8 text-white md:flex md:items-center md:justify-between md:p-12"><div><p className="text-sm font-bold uppercase tracking-[.18em]" style={{ color: selected.soft }}>Ready when you are</p><h2 className="mt-3 text-3xl font-black">A focused next step for every client.</h2></div><a className="mt-6 inline-block rounded-full px-6 py-3 font-bold text-white md:mt-0" style={{ backgroundColor: selected.color }} href="mailto:tairanos8@gmail.com">{selected.action}</a></div></section></main>;
}
